# Usa la imagen oficial de Rust como base
FROM ejemplo:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/nombreproyecto

# Copia el resto de los archivos del proyecto al contenedor desde la ruta 
COPY ./nombreproyecto ./ 

# CMD por defecto para mantener el contenedor vivo (útil para docker exec)
CMD [""]


